# Generated by Django 5.2.8 on 2025-11-13 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salas_online', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sala',
        ),
    ]
